### PR TITLE
Update organizerguide.md

### PR DESCRIPTION
**Pull request by akhmerov**
Opening on behalf of @giulia-pacchioni:

> I have added a paragraph stating specifically how the VSF will help with the organization of events, polished the text a bit and introduced a couple of changes we had discussed (linking to moderator guide, mentioning geographical, seniority and gender balance).

> Now we can remove my ill-formed old pull request :)

### CODE REVIEW

**Comment by akhmerov** [comment]
@giulia-pacchioni since you based your changes not on the latest version, but rather on the one before @babaks77 edits (I think), there are conflicts. Some of those are straightforward to resolve, but two chunks have diverged more. Can you please compose a single version out of these two chunks:

```
<<<<<<< HEAD
- Decide on the scale/format of the event. Some things to consider: 
  - length of the event
  - number of talks
  - whether to have only invited talks or also contributed talks
  - whether to have a poster session
  - whether to have meeting with speakers (especially useful to students and junior scientists)
- Make a list of possible speakers to approach
- Decide on a date (should be at least 2 months in the future, so that you can find the speakers and announce the event properly)
- Submit an application to us
- Approach the speakers, invite submissions for the contributed talks (if you have them) and start making a program
- Find the moderators for the talks
- Advertise the event
- Build a webpage / create a registration and if applicable abstract submission form.
- Email the Zoom link to the registered participants one or two days before the event
- Test the software with the moderators and speakers the day before the event
- Run the event and have fun!
=======
- Decide on the scale/format of the event: number of speakers and length of talks
- Make a list of possible speakers to approach
- Decide on a date (should be at least 2 months in the future, so that you can find the speakers and announce the event properly)
- Submit an application to us
- After the time slot is reserved, approach the speakers, invite submissions for contributed talks and posters (if you have them), make a program, and create a webpage
- Advertise the event
- Find the moderators for the talks, ensure that the moderators and the speakers try the software in advance
- Approve participant applications for registration.
- Run the event
- Summarize your experience
>>>>>>> Update organizerguide.md
```

and these two:

```
<<<<<<< HEAD
We will announce the session to anyone signed up to our mailing list and publicly through our Twitter account, but since you have connections in your specific community, the most effective advertising will come from you. Use your resources. For example you can consider:

- Announcing the session to your colleagues via email
- Posting about it on social media

We of course ask you to be considerate and avoid spamming your colleagues.

### Final preparation: 1 week before the session

In the virtual conference setting, moderators play a vital role. Find moderators for your event. The moderator's role is demanding, and we recommend finding more than one person to fill it. For example, you might want to have one person in charge of introducing the speakers and moderate the question, and a second one checking who want to asks questions and making sure everything is running smoothly. See our [Moderator Guide](https://virtualscienceforum.org/#/moderatorguide) for more detailed information.

Set up an appointment with the speakers and the moderators to introduce them to the platform. 
=======
We will announce the event to anyone signed up to our mailing list and through our twitter account, but since you have community connections, you hold the advertising job. Use your resources. For example you can consider:

- Announcing the event to your colleagues via email
- Mentioning it during your travel
- Posting about it on social media

This aspect is not different from traditional conferences: mailing lists, professional contacts, flyers, social media etc. We of course ask you to be considerate and avoid spamming your colleagues.

### Final preparations: 1 week before the event

In the virtual conference setting moderators play a vital role. Find moderators for your event. The [moderator's role](https://virtualscienceforum.org/#/moderatorguide) is demanding, and we recommend finding more than one person to fill it. The moderators should also be familiar with the sesion topic.

Set up an appointment with the speakers and the moderators to introduce them to the platform. 
We can accomodate events with up to 500 participants using the meeting format in Zoom, and up to 1,000 using the webinar format in Zoom. If you have more attendees than these, you can consider streaming the event on the VSF website for those who cannot join the Zoom event, or to select applicants.
>>>>>>> Update organizerguide.md
```

If you can write the result in comments, I'll merge the edits, and we're done.

**Comment by akhmerov** [comment]
Alternatively (if that's easier for you) you can press the "resolve conflicts" button below. You'll be presented with a document where you need to combine all the conflicting edits into a single version. After you choose the correct one and commit, all should be good.

**Comment by giulia-pacchioni** [comment]
I have included my changes in the current Master branch and committed the updated version.

**Comment by akhmerov** [comment]
Great, thanks! I'm closing this (all changes are on master).

**Pull request closed without merging**
