### PR TITLE
no instruction on what to put for the issue submission

### PR DESCRIPTION
**Pull request by vfatemi**
I made a suggestion under "title" to put the talk title in the issue title, but maybe there is a better way.

### CODE REVIEW

**Comment by akhmerov** [comment]
Hm, we aren't using the title at all. Could just set the default title to be "speakers' corner talk application"

**Comment by akhmerov** [comment]
The link now should contain the proposed title, try clicking from https://virtualscienceforum.org/#/speakers-corner and close if you're happy with the outcome

**Comment by vfatemi** [comment]
I edited to capitalize the "C" in corner where applicable. Otherwise looks good. It seems you edited separately from this issue? If so, the attached pull request is then outdated.

**Comment by akhmerov** [comment]
Indeed. Sorry about separate editing: the issue description is automatically generated from the question list—that's why I did the change elsewhere.

I'm closing this as addressed.

**Pull request closed without merging**
