### PR TITLE
a "who we are" page

### PR DESCRIPTION
**Pull request by vfatemi**
please check for appropriate names, institution associations, and spellings...

### CODE REVIEW

**Comment by akhmerov** [comment]
Great idea!

I have one point to raise though, namely I suggest to make the language more inclusive. There are two things that matter: who is responsible (let's say "admins"), and who contributed over the whole history. I would rather not use the term "founding members"—that group will never change.

At this point effectively everyone is an admin, so it's probably too early to make a distinction between the two groups, but we could call the group "contributors" or something like that.

**Comment by akhmerov** [comment]
How about something like:

"Virtual Science Forum is a collaborative effort of the research community. Below is the list of contributors."

**Comment by vfatemi** [comment]
That sounds good to me for the current situation. 

Eventually we may also want to reorganize these names into groups like "scientific committee" and other teams, if we end up specializing our roles and want to make that public.

**Comment by akhmerov** [comment]
@vfatemi absolutely, we'll get there.

I'm merging for now, feel free to refine.

**Pull request merged**
