### PR TITLE
Update whoweare.md

### PR DESCRIPTION
**Pull request by greplova**
I put Alberto under T (following the logic that Evert is under N).

### CODE REVIEW

**Comment by everthemore** [comment]
Thank you! I added Stefan Bretzel to the list of former contributors. 
Looks good to merge, we can always add more afterwards!

**Comment by akhmerov** [comment]
Late to the party: shall we add a definition of "current" somewhere? E.g. "Active in the last 3 months"?

**Comment by everthemore** [comment]
I have no preference regarding that. What does 'active' mean though?

**Comment by vfatemi** [comment]
Attendance at org meetings would seem a reasonable metric.

**Comment by akhmerov** [comment]
I don't think we need to be too specific with that (responding to issues, doing housekeeping, etc would also be fine).

**Comment by greplova** [comment]
If we put such rigorous statement (like the 3 months thing) we should also make sure it’s always 100% up to date - for this reason I would prefer to keep it more relaxed and just take stock when it comes up like we did just now.

**Comment by vfatemi** [comment]
Perhaps a "last updated on [date]" comment could cover that?

**Comment by everthemore** [comment]
That (@vfatemi) sounds like a fair suggestion and compromise to me

**Pull request merged**
