### PR TITLE
add reproducibility workshop page

### PR DESCRIPTION
**Pull request by akhmerov**
Related to #578

### CODE REVIEW

**Comment by brianqskinner** [comment]
Hello, thanks for putting together this web page. I have just a few suggested corrections:

The workshop is taking place on **Thursday, March 2** and not March 3 as currently listed.

In the last paragraph of the workshop description, "social and medical sciences" should be "social and biomedical sciences".

The clickable link on this page https://virtualscienceforum.org/pr-583/ has a typo: "reprodicibility" instead of "reproducibility".

**Comment by akhmerov** [comment]
All fixed. Should I also add the program?

**Comment by akhmerov** [comment]
The registration and the schedule are up; please check the same link again.

**Comment by brianqskinner** [comment]
Thank you Anton. They look good to me.

I have written to the speakers to ask for titles for their talks; I will
write to you with an update as soon as I have them.

**Comment by brianqskinner** [comment]
I will comment with the talk titles here as well, in case I added them before to the wrong thread earlier. (And apologies for my relative ignorance about github):

Simine Vazhire (University of Melbourne): "What is a replication crisis and how do I know if I'm in one? Lessons from Psychology"

James Hamlin (University of Florida): "Extracting data from scientific publications"

Vincent Mourik (Forschungszentrum Jülich): "Non reproducible claims in Majorana research"

I would appreciate if you can help me add them to the web page.

**Comment by akhmerov** [comment]
Apologies for the delay, all done.

**Pull request merged**
