### PR TITLE
Initial mailing list signup form

### LINKED ISSUE #143: Allow mailing list subscriptions
* [x] Set up a different repository for 'action' related code
    * [x] Check that the other repository has limited secrets access (so not all members by default)
* [x] Store all API secrets/tokens in that repository github secret storage
* [x] Set up cloud functions for sending requests to Mailgun
* [x] Set up a recaptcha v2
* [x] Set up origin checking of signup request
* [x] Embed a form in doscify
* [ ] Stretch goal: figure out what to do with re-subscriptions (by default mailgun won't mark people as subscribed if they unsubbed before)

### PR DESCRIPTION
**Pull request by everthemore**
Closes #143 #140

### CODE REVIEW

**Comment by akhmerov** [comment]
I think this actually already looks quite good. We should clear form on success (`form.reset()`). We'd also want to implement UI for indicating the status. This looks decent: https://www.w3schools.com/howto/howto_js_alert.asp , @everthemore do you agree?

**Comment by everthemore** [comment]
Looks good to me! Fits the sign-up form sign-up button perfectly :)

**Comment by everthemore** [comment]
I've added such alerts @akhmerov, and also clear the form after a successful (from the form's point of view) submit. I'd say the form side of things is pretty much done.

**Comment by akhmerov** [comment]
Disabling the "submit" button and re-enabling it via a form `onChange` listener seems to be better UI. Also we should have the general list checked by default (we should assume that people want to sign up for at least one mailing list at once).

**Comment by akhmerov** [comment]
I'm taking a look at these.

**Comment by akhmerov** [comment]
@everthemore check this out. I'm happy with what we have now. The only remaining thing is deciding from where we should link this.

**Comment by everthemore** [comment]
Great @akhmerov! You wanted to have the signup button disabled when no lists are checked rather than an error msg, should I have a go at that? As for the placement of the signup, perhaps a 'Stay up to date!' section or similar on the main page?

**Comment by akhmerov** [comment]
> You wanted to have the signup button disabled when no lists are checked rather than an error msg, should I have a go at that?

Right, I have since learned that `<input required>` is the semantically best way to achieve this goal.

> As for the placement of the signup, perhaps a 'Stay up to date!' section or similar on the main page?

Sounds good. I'll add this, but we should hold off merging until the worker is ready. Will you have some bandwidth to finish the remaining bits there?

**Comment by akhmerov** [comment]
Here's what I have, what do ppl think?

image

**Comment by everthemore** [comment]
> Right, I have since learned that `<input required>` is the semantically best way to achieve this goal.

Those are indeed on the name and address fields, but I hadn't yet figured out how to make a group of checkboxes such that at least one is required. So I did that with js rather than the nicer UI you get with the required attribute.

**Comment by akhmerov** [comment]
I think we can always improve on that later. We might rewrite the whole
form when moving to a new website anyway.

**Comment by everthemore** [comment]
Sounds good. I'll put some more effort into the worker in the following days.

**Comment by akhmerov** [comment]
@everthemore merge and test?

**Pull request merged**
