### PR TITLE
Dispatching request for zoom talk scheduling to automation repo

### PR DESCRIPTION
**Pull request by everthemore**

### CODE REVIEW

**Comment by akhmerov** [comment]
I propose to make this a separate action that triggers on any push to master.

**Comment by everthemore** [comment]
Because you envision multiple dispatches upon pushes to master? Any push to master doesn't need to trigger the zoom scheduling?

**Comment by akhmerov** [comment]
Hm, after a second thought, there's indeed no reason to arrange for a scenario that we don't aim to support yet, so let's indeed keep it this way.

**Comment by everthemore** [comment]
@akhmerov YOLO merge tomorrow? We could merge now~ish, but I won't be able to debug in realtime tonight; may not be necessary though; what say you?

**Comment by akhmerov** [comment]
Not really needed: we can (and should) trigger the other workflow manually.

**Pull request merged**
