### PR TITLE
Superconducting-workshop

### PR DESCRIPTION
**Pull request by akhmerov**
Workshop page for #498

### CODE REVIEW

**Comment by akhmerov** [comment]
@ViktoriiaKornich here's the current workshop page https://virtualscienceforum.org/pr-499/unconventional-superconductivity/

**Comment by ViktoriiaKornich** [comment]
@akhmerov thank you! There is something wrong with the time. Our schedule starts at 14:00 and ends at 18:10. Right now the correct time is only 14:00 near the short description. I am not sure, why, I put the correct times yesterday. Do you know, how to correct it?

**Comment by ViktoriiaKornich** [comment]
Also, March 31 Young Researchers' session should last for 1 hour, so until 18:00. I really don't know, what happened with time, probably I programmed it somehow wrong yesterday. Sorry!

**Comment by akhmerov** [comment]
That's the timezone difference, and easy to fix. Does everything else look good for now?

**Comment by ViktoriiaKornich** [comment]
Yes, thank you! Only the time zone difference and the concluding remarks on March 31 should be at 18:00.

**Comment by ViktoriiaKornich** [comment]
Sorry, maybe I can somehow help? We already feel uncomfortable not to update our speakers about the webpage etc. If it is easy to fix, maybe somebody from VSF can do it? I have put final corrections to time and created a pull request, so the only thing left is timezone. However, I don't know how to do it. I wonder, if it is not easy to fix, maybe I will just subtract two hours from the time that is displayed? @akhmerov @adelatorreduran @giulia-pacchioni

**Comment by adelatorreduran** [comment]
@ViktoriiaKornich do you want to add a contact email to the webpage?

**Comment by akhmerov** [comment]
Also, the times are fixed now, please double-check. If you prefer, we can give you an email `@virtualscienceforum.org`

**Comment by ViktoriiaKornich** [comment]
Thank you very much! You can give just my work email, I don't think I will be spammed. My work email is viktoriia.kornich@physik.uni-wuerzburg.de

**Comment by adelatorreduran** [comment]
Added, I will start the merge pull request. 

Also, please use the link below to open a new issue for the mailing list announcement. Don't worry about the automatization formatting, we will edit it. Just make sure to include whatever information you deem convenient. 

https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md&title=superconducting%20workshop%20announcement%20

**Comment by ViktoriiaKornich** [comment]
Just to make sure, I understand, I should put the text into the mailing list, right? It is an advertisement for people, who subscribed, right?

**Comment by adelatorreduran** [comment]
You only need to write the "body" of the email. This email will be sent to the vsf mailing list to broadly advertise your conference :)

**Comment by ViktoriiaKornich** [comment]
OK, sure, I will look up at other advertisements I have received from VSF and write something in that style.

**Comment by akhmerov** [comment]
An organizational remark: let's discuss organizational matters in the planning issue #498, so that we don't lose track.

**Pull request merged**
