### PR TITLE
Create SPM_workshop_invitation.md

### PR DESCRIPTION
**Pull request by giulia-pacchioni**
Invitation email for SPM workshop. Here is the text:

Dear Colleagues and Friends, 

We hope this message finds you well. With conferences and events cancelled, we thought that organizing a virtual workshop on scanning tunnelling microscopy and atomic force microscopy would be a good way to keep in touch with our community, stay up to date on the latest results and have some fruitful discussions. We would very much like to see you there!

**The workshop will be held on Thursday, June 18th, 9:00 - 13:00   CEST on Zoom**

We will have three invited talks given by Taeyoung Choi, Katharina Franke and Jascha Repp, followed by a live poster session with a Zoom discussion for each poster.

You can find the details of the event on our website (https://sites.google.com/view/virtualspm). The event is organized with support from the Virtual Science Forum (https://virtualscienceforum.org/#/). Attendance is free, but don’t forget to REGISTER (https://sites.google.com/view/virtualspm/registration ).

Please spread the voice and feel free to forward this message to whoever you think might be interested.

We are looking forward to (virtually) seeing you on June 18th!

Best wishes,
The organizing committee

Fabio Donati, Ewha Womans University
Fabian Natterer, University of Zurich
Giulia Pacchioni, Nature Reviews Materials
Marina Pivetta, EPFL Lausanne
Aparajita Singha, Max Planck Institute for solid state research

### CODE REVIEW

**Comment by akhmerov** [comment]
I'm wondering: most recipients know about virtual conferences, so the first sentence is probably very familiar. At the same time, the invitation does not say much about the scope of the conference. Is there something you could add?

**Comment by akhmerov** [comment]
Also: since the email will be sent from the VSF mailing list, I'd like to sign as VSF team on behalf of the organizers. Is that OK?

**Comment by giulia-pacchioni** [comment]
It is true probably the intro is not needed, and we can jump into the topic by saying 'We would like to invite you to a virtual workshop on new developments in scanning tunneling microscopy and atomic force microscopy'. We are keeping the scope broad to encourage variety in the submitted posters.

Great for the suggested signature, it makes more sense than my original suggestion. 

Thanks!

**Comment by akhmerov** [comment]
@giulia-pacchioni, I've rephrased the announcement a bit and emailed it. Hope that's OK.

**Comment by giulia-pacchioni** [comment]
It's great thanks!

**Pull request merged**
